In [117]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

from sklearn.datasets import load_diabetes
import random

In [118]:
X,y = load_diabetes(return_X_y=True)

In [119]:
X[:10]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632753, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567042, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286131, -0.02593034],
       [-0.08906294, -0.04464164, -0.01159501, -0.03665608,  0.01219057,
         0.02499059, -0.03603757,  0.03430886,  0.02268774, -0.00936191],
       [ 0.00538306, -0.04464164, -0.03638469,  0.02187239,  0.00393485,
         0.01559614,  0.00814208, -0.00259226, -0.03198764, -0.04664087],
       [-0.09269548, -0.04464164, -0.04069594, -0.01944183, -0.06899065,
        -0.07928784,  0.04127682, -0.0763945 , -0.04117617, -0.09634616],
       [-0.04547248,  0.05068012, -0.04716281, -0.01599898, -0.04009564,
        -0.02480001,  0.00077881, -0.03949338

In [120]:
y[:10]

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310.])

## Custom code

In [121]:
class SGD:
    def __init__(self,lr,epoch):
        self.lr = lr
        self.epoch = epoch
        self.coef_ = None
        self.intercept_ = None
    
    def fit(self,x,y):
        self.coef_ = np.ones(x.shape[1])
        self.intercept_ = 0

        for i in range(self.epoch):
            indices = np.random.permutation(x.shape[0])
            for ind in indices:
                yhat = np.dot(x[ind], self.coef_) + self.intercept_
                self.intercept_ = self.intercept_ - self.lr * (-2 * (y[ind] - yhat))

                self.coef_ = self.coef_ - self.lr * (-2 * (np.dot((y[ind] - yhat),x[ind])))
        print(self.intercept_,self.coef_)

        
    def predict(self,x):
        return np.dot(x, self.coef_) + self.intercept_


In [122]:
np.random.permutation(10)

array([8, 6, 7, 4, 1, 9, 0, 2, 3, 5])

In [123]:
sgd = SGD(0.01, 100)
sgd.fit(X,y)

154.009788419228 [  10.88069618 -185.47304904  476.27674956  296.94300378  -37.75520848
 -100.69918006 -205.42666135  130.46794041  395.92536444  123.35632171]


In [124]:
X.shape

(442, 10)

## Builtin

In [125]:
from sklearn.linear_model import SGDRegressor

In [126]:
reg = SGDRegressor(max_iter=100,learning_rate='constant', eta0=0.01)
reg.fit(X,y)

SGDRegressor(learning_rate='constant', max_iter=100)

In [127]:
reg.intercept_,reg.coef_

(array([156.6473863]),
 array([  37.11539937,  -96.66660529,  368.55614645,  243.55727462,
           5.89348522,  -38.55575903, -185.30773624,  142.14564679,
         312.36576896,  141.91329722]))